<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "me_google_calendar"
 *
 * Auto generated by Extension Builder 2012-12-14
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Google Calendar',
	'description' => 'Includes the jQuery Plugin FullCalendar, which generates a skinable Calendar with different views (month, week, day, week list, day list) from Google Calendar XML Feed(s) - now with extbase/fluid',
	'category' => 'plugin',
	'author' => 'Alexander Grein',
	'author_email' => 'mail@mediaessenz.de',
	'author_company' => 'MEDIA::ESSENZ',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '3.0.0',
	'constraints' => array(
		'depends' => array(
			'extbase' => '6.0',
			'fluid' => '6.0',
			'typo3' => '6.0',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>